MK_WERROR: Downgrade an error to an information message
Summary:
In 7fa2f2a62f04f095e1e27ad55aa22a8f59b1df8f, I replaced all uses of NO_WERROR
with MK_WERROR in the src repo, but this file is also used by ports where
this .error is causing problems.

I'm not sure how many ports use NO_WERROR, so this might be needed if applying
something like https://reviews.freebsd.org/rP561055 to all problematic ports
is not feasible

Reported By: tijl

Reviewers: tijl

Subscribers: bdrewery, emaste

Differential Revision: https://reviews.freebsd.org/D28084