qeueue.h: Add {SLIST,STAILQ,LIST,TAILQ}_END()
Summary:
This fixes the following warning (which should arguable be an error since
it results in a function call to an undefined function):

===> usr.sbin/ntp/libntpevent (all)
.../contrib/libevent/buffer.c:495:16: warning: implicit declaration of function 'LIST_END' is invalid in C99 [-Wimplicit-function-declaration]
             cbent != LIST_END(&buffer->callbacks);
                      ^
.../contrib/libevent/buffer.c:495:13: warning: comparison between pointer and integer ('struct evbuffer_cb_entry *' and 'int') [-Wpointer-integer-compare]
             cbent != LIST_END(&buffer->callbacks);
             ~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Test Plan: Compiles and boots (RISCV64)

Reviewers: jhb

Differential Revision: https://reviews.freebsd.org/D27151